import { StyleSheet } from 'react-native';

import { colors, fonts } from '@/constants/theme';

export const dashboardStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  stickyNavWrap: {
    paddingTop: 10,
    paddingBottom: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 16,
    zIndex: 20,
  },
  topBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBarBrand: {
    fontSize: 22,
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  userBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 'auto',
    marginRight: 10,
  },
  userInitialsCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f4d9d9',
    borderWidth: 1,
    borderColor: '#d9a3a3',
  },
  userInitialsText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  userRolePill: {
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eef4ff',
    borderWidth: 1,
    borderColor: '#8bb2ff',
  },
  userRoleText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#2454c6',
  },
  burgerButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  burgerButtonActive: {
    backgroundColor: colors.primary,
  },
  burgerLine: {
    width: 18,
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.text,
    marginVertical: 2,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 66,
    right: 16,
    width: 220,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  menuOverlayWrap: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: -1000,
    left: 0,
  },
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  menuRowButton: {
    minHeight: 50,
    paddingHorizontal: 16,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuRowButtonActive: {
    backgroundColor: colors.primary,
    borderBottomColor: '#8b1c1f',
  },
  menuRowButtonLogout: {
    backgroundColor: colors.dangerBackground,
    borderBottomWidth: 0,
  },
  menuRowText: {
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  menuRowTextActive: {
    color: colors.white,
  },
  menuRowTextInactive: {
    color: colors.text,
  },
  menuRowTextLogout: {
    color: colors.dangerText,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  heroCard: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 14,
  },
  appName: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 28,
    fontFamily: fonts.bold,
    color: colors.white,
  },
  heroSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.regular,
    color: '#f7dede',
    marginTop: 8,
  },
  screenTitle: {
    fontSize: 26,
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: 6,
  },
  screenTitleCentered: {
    fontSize: 26,
    fontFamily: fonts.bold,
    color: colors.text,
    textAlign: 'left',
  },
  screenTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    minHeight: 44,
  },
  inboxShortcutButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleSpacer: {
    width: 40,
    height: 40,
  },
  inboxShortcutDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: '#dc2626',
    borderWidth: 1,
    borderColor: colors.surface,
  },
  screenSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  chipApproved: {
    backgroundColor: colors.successBackground,
    borderColor: colors.successBorder,
  },
  chipOccupied: {
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
  },
  chipPending: {
    backgroundColor: '#fff7ed',
    borderColor: '#fdba74',
  },
  chipRejected: {
    backgroundColor: colors.dangerBackground,
    borderColor: colors.dangerBorder,
  },
  chipActive: {
    backgroundColor: '#fff1f1',
    borderColor: '#f2b4b4',
  },
  chipText: {
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  chipTextApproved: {
    color: colors.successText,
  },
  chipTextOccupied: {
    color: '#1d4ed8',
  },
  chipTextPending: {
    color: '#c2410c',
  },
  chipTextRejected: {
    color: colors.dangerText,
  },
  chipTextActive: {
    color: colors.primary,
  },
  reservationTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.text,
    marginTop: 14,
  },
  reservationMeta: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginTop: 4,
  },
  reservationPurpose: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.bold,
    color: colors.text,
    marginTop: 8,
  },
  reservationActionButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  reservationActionButtonStart: {
    backgroundColor: '#b91c1c',
  },
  reservationActionButtonFinish: {
    backgroundColor: '#2563eb',
  },
  reservationActionButtonDisabled: {
    opacity: 0.7,
  },
  reservationActionButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
    marginBottom: 6,
  },
  metricCard: {
    width: '50%',
    paddingHorizontal: 6,
    marginBottom: 12,
  },
  metricInner: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    minHeight: 114,
  },
  metricLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
  metricValue: {
    fontSize: 28,
    fontFamily: fonts.bold,
    color: colors.primary,
    marginTop: 12,
  },
  menuButton: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 12,
  },
  menuTitle: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: colors.text,
  },
  menuDescription: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginTop: 6,
  },
  listItem: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 12,
  },
  accountPairRow: {
    flexDirection: 'row',
    gap: 12,
  },
  accountPairItem: {
    flex: 1,
  },
  mutedLabel: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.mutedText,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 8,
  },
  placeholderCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
  },
  placeholderText: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
  actionButton: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  actionButtonInset: {
    marginHorizontal: 16,
  },
  actionButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 10,
    marginHorizontal: 16,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
});
