import { StyleSheet } from 'react-native';

import { colors, fonts } from '@/constants/theme';

export const dashboardStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  stickyNavWrap: {
    paddingTop: 10,
    paddingBottom: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 16,
    zIndex: 20,
  },
  topBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBarBrand: {
    fontSize: 22,
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  userBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 'auto',
    marginRight: 10,
  },
  userInitialsCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f4d9d9',
    borderWidth: 1,
    borderColor: '#d9a3a3',
  },
  userInitialsText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  userRolePill: {
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eef4ff',
    borderWidth: 1,
    borderColor: '#8bb2ff',
  },
  userRoleText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: '#2454c6',
  },
  burgerButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  burgerButtonActive: {
    backgroundColor: colors.primary,
  },
  burgerLine: {
    width: 18,
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.text,
    marginVertical: 2,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 66,
    right: 16,
    width: 220,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  menuOverlayWrap: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: -1000,
    left: 0,
  },
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  menuRowButton: {
    minHeight: 50,
    paddingHorizontal: 16,
    justifyContent: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuRowButtonActive: {
    backgroundColor: colors.primary,
    borderBottomColor: '#8b1c1f',
  },
  menuRowButtonLogout: {
    backgroundColor: colors.dangerBackground,
    borderBottomWidth: 0,
  },
  menuRowText: {
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  menuRowTextActive: {
    color: colors.white,
  },
  menuRowTextInactive: {
    color: colors.text,
  },
  menuRowTextLogout: {
    color: colors.dangerText,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  heroCard: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    padding: 20,
    marginBottom: 14,
  },
  appName: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.white,
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 28,
    fontFamily: fonts.bold,
    color: colors.white,
  },
  heroSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.regular,
    color: '#f7dede',
    marginTop: 8,
  },
  screenTitle: {
    fontSize: 26,
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: 6,
  },
  screenTitleCentered: {
    fontSize: 26,
    fontFamily: fonts.bold,
    color: colors.text,
    textAlign: 'left',
  },
  sectionTitleWrap: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: 10,
    flexShrink: 1,
  },
  screenTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    minHeight: 44,
  },
  inboxShortcutButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleSpacer: {
    width: 40,
    height: 40,
  },
  inboxShortcutDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: '#dc2626',
    borderWidth: 1,
    borderColor: colors.surface,
  },
  screenSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginBottom: 18,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.text,
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  chipApproved: {
    backgroundColor: colors.successBackground,
    borderColor: colors.successBorder,
  },
  chipOccupied: {
    backgroundColor: '#eff6ff',
    borderColor: '#93c5fd',
  },
  chipPending: {
    backgroundColor: '#fff7ed',
    borderColor: '#fdba74',
  },
  chipExpired: {
    backgroundColor: '#f3f4f6',
    borderColor: '#d1d5db',
  },
  chipRejected: {
    backgroundColor: colors.dangerBackground,
    borderColor: colors.dangerBorder,
  },
  chipActive: {
    backgroundColor: '#fff1f1',
    borderColor: '#f2b4b4',
  },
  chipText: {
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  chipTextApproved: {
    color: colors.successText,
  },
  chipTextOccupied: {
    color: '#1d4ed8',
  },
  chipTextPending: {
    color: '#c2410c',
  },
  chipTextExpired: {
    color: '#4b5563',
  },
  chipTextRejected: {
    color: colors.dangerText,
  },
  chipTextActive: {
    color: colors.primary,
  },
  reservationTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.text,
    marginTop: 14,
  },
  reservationMeta: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginTop: 4,
  },
  reservationPurpose: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.bold,
    color: colors.text,
    marginTop: 8,
  },
  reservationActionButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  reservationActionButtonStart: {
    backgroundColor: '#b91c1c',
  },
  reservationActionButtonFinish: {
    backgroundColor: '#2563eb',
  },
  reservationActionButtonDisabled: {
    opacity: 0.7,
  },
  reservationActionButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  inlineSecondaryButton: {
    width: '100%',
    backgroundColor: colors.surface, 
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  inlineSecondaryButtonText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
    marginBottom: 6,
  },
  metricCard: {
    width: '50%',
    paddingHorizontal: 6,
    marginBottom: 12,
  },
  metricInner: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    minHeight: 114,
  },
  metricLabel: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
  metricValue: {
    fontSize: 28,
    fontFamily: fonts.bold,
    color: colors.primary,
    marginTop: 12,
  },
  menuButton: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 12,
  },
  menuTitle: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: colors.text,
  },
  menuDescription: {
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginTop: 6,
  },
  listItem: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 16,
    marginBottom: 12,
  },
  reservationContent: {
    width: '100%',
  },
  reservationContentWithTrailingAction: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
    width: '100%',
  },
  reservationContentBody: {
    flex: 1,
    minWidth: 0,
  },
  dashboardGroupItem: {
    marginBottom: 12,
  },
  accountPairRow: {
    flexDirection: 'row',
    gap: 12,
  },
  accountPairItem: {
    flex: 1,
  },
  mutedLabel: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.mutedText,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 0,
  },
  placeholderCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 20,
  },
  placeholderText: {
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
  actionButton: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  backButtonContainer: {
    marginHorizontal: 16,
    marginTop: 0,
  },
  actionButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 10,
    marginHorizontal: 16,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
  textLink: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 11,
    textDecorationLine: 'underline',
    marginRight: 8,
  },
  filterTabsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 18,
  },
  reservationFilterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginTop: -2,
    marginBottom: 12,
  },
  reservationRadioChip: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignSelf: 'flex-start',
  },
  reservationRadioChipSelected: {
    borderColor: '#e7aaaa',
    backgroundColor: '#fbf2f2',
  },
  reservationRadioOuter: {
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reservationRadioOuterSelected: {
    borderColor: colors.primary,
  },
  reservationRadioInner: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  reservationRadioText: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 12,
    flexShrink: 1,
  },
  filterTabButton: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.filterChipInactiveBorder,
    backgroundColor: colors.surface,
  },
  filterTabButtonActive: {
    backgroundColor: colors.filterChipActive,
    borderColor: colors.filterChipActiveBorder,
  },
  filterTabButtonText: {
    fontSize: 11,
    fontFamily: fonts.bold,
    color: colors.text,
    flexShrink: 1,
  },
  filterTabButtonTextActive: {
    color: colors.white,
  },
  filterTabBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 5,
    marginLeft: 6,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.filterChipInactive,
  },
  filterTabBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  filterTabBadgeText: {
    fontSize: 10,
    fontFamily: fonts.bold,
    color: colors.secondary,
  },
  filterTabBadgeTextActive: {
    color: colors.white,
  },
  reservationHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  reservationHeaderContent: {
    flex: 1,
    minWidth: 0,
  },
  reservationRoomNameWrap: {
    paddingRight: 88,
  },
  reservationRoomName: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: colors.text,
    flexShrink: 1,
    marginTop: -6,
    marginBottom: 6,
  },
  reservationHeaderBadge: {
    flexShrink: 0,
    alignSelf: 'flex-start',
  },
  reservationChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  reservationActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 14,
  },
  reservationOutlineButton: {
    minWidth: 120,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  reservationOutlineButtonDanger: {
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerBackground,
  },
  reservationOutlineButtonPrimary: {
    borderColor: '#93c5fd',
    backgroundColor: '#eff6ff',
  },
  reservationOutlineButtonText: {
    fontSize: 13,
    fontFamily: fonts.bold,
  },
  reservationOutlineButtonTextDanger: {
    color: colors.dangerText,
  },
  reservationOutlineButtonTextPrimary: {
    color: '#1d4ed8',
  },
  inboxList: {
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  inboxListFullWidth: {
    marginHorizontal: -16,
  },
  inboxNotificationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  inboxNotificationRowUnread: {
    backgroundColor: '#fffafa',
  },
  inboxNotificationRowLast: {
    borderBottomWidth: 0,
  },
  inboxNotificationIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    backgroundColor: '#c9f1da',
  },
  inboxNotificationIconWrapRejected: {
    backgroundColor: '#fee2e2',
  },
  inboxNotificationIconWrapPending: {
    backgroundColor: '#ffedd5',
  },
  inboxNotificationContent: {
    flex: 1,
    minWidth: 0,
  },
  inboxNotificationHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  inboxNotificationHeadingBlock: {
    flex: 1,
    minWidth: 0,
  },
  inboxNotificationMetaBlock: {
    alignItems: 'flex-end',
    flexShrink: 0,
    maxWidth: 130,
  },
  inboxNotificationTitle: {
    flex: 1,
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.text,
    lineHeight: 21,
  },
  inboxNotificationBody: {
    fontSize: 14,
    lineHeight: 21,
    fontFamily: fonts.regular,
    color: colors.secondary,
    marginTop: 4,
  },
  inboxNotificationTimestamp: {
    fontSize: 12,
    lineHeight: 18,
    fontFamily: fonts.bold,
    color: colors.mutedText,
  },
  inboxNotificationArrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 0,
  },
  inboxNotificationArrowSpacer: {
    flex: 1,
  },
  inboxNotificationExpanded: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 4,
  },
  inboxNotificationDetailText: {
    fontSize: 13,
    lineHeight: 19,
    fontFamily: fonts.regular,
    color: colors.secondary,
  },
  inboxNotificationActionButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d9a3a3',
    backgroundColor: '#fff1f1',
  },
  inboxNotificationActionButtonDisabled: {
    opacity: 0.6,
  },
  inboxNotificationActionButtonText: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.primary,
  },
  inboxPanelEmpty: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingVertical: 22,
  },
});
