import { StyleSheet } from "react-native";

import { colors, fonts } from "@/constants/theme";
import { TIME_WHEEL_ITEM_HEIGHT } from "./helpers";

const styles = StyleSheet.create({
  wrapper: {},
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  searchInputWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
  },
  searchIcon: {
    width: 18,
    height: 18,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  searchIconCircle: {
    width: 10,
    height: 10,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.mutedText,
  },
  searchIconHandle: {
    position: "absolute",
    width: 7,
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.mutedText,
    transform: [{ rotate: "45deg" }, { translateX: 5 }, { translateY: 5 }],
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 0,
    paddingVertical: 12,
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 14,
  },
  filterButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  filterButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  filterIcon: {
    width: 14,
    height: 12,
    justifyContent: "space-between",
  },
  filterIconLine: {
    height: 2,
    borderRadius: 999,
    backgroundColor: colors.text,
  },
  filterIconLineActive: {
    backgroundColor: colors.white,
  },
  filterIconLineTop: {
    width: 14,
  },
  filterIconLineMiddle: {
    width: 10,
  },
  filterIconLineBottom: {
    width: 6,
  },
  filterButtonActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  filterButtonText: { color: colors.text, fontFamily: fonts.bold, fontSize: 13 },
  filterButtonTextActive: { color: colors.white },
  filterCard: {
    marginTop: 12,
    marginBottom: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.subtleBackground,
    padding: 14,
  },
  filterSectionTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
    marginBottom: 10,
  },
  radioGroup: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  radioRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  radioRowSelected: {
    borderColor: "#e7aaaa",
    backgroundColor: "#fbf2f2",
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterSelected: {
    borderColor: colors.primary,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  radioText: { color: colors.text, fontFamily: fonts.bold, fontSize: 13 },
  toggleCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  toggleTextBlock: { flex: 1, paddingRight: 12 },
  toggleTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 16 },
  toggleSubtitle: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 12,
    marginTop: 4,
  },
  weekdayCalendarRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 10,
    marginBottom: 16,
  },
  weekdayCalendarButton: {
    width: "31%",
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  weekdayCalendarButtonSelected: { backgroundColor: "#f9e3e3", borderColor: "#e7aaaa" },
  weekdayCalendarText: { color: colors.text, fontFamily: fonts.bold, fontSize: 14 },
  weekdayCalendarTextSelected: { color: colors.primary },
  inputGrid: { flexDirection: "row", justifyContent: "space-between", gap: 12, marginBottom: 16 },
  inputBlock: { flex: 1 },
  inputLabel: { color: colors.text, fontFamily: fonts.bold, fontSize: 14, marginBottom: 8 },
  inputWithAction: {
    position: "relative",
    justifyContent: "center",
  },
  filterInput: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text,
    fontFamily: fonts.regular,
    fontSize: 14,
  },
  filterInputWithIcon: {
    paddingRight: 48,
  },
  inlineTimeInputShell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  inlineTimeHourInput: {
    width: 30,
    paddingVertical: 0,
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
    textAlign: "center",
  },
  inlineTimeSeparator: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  inlineTimeMinuteInput: {
    width: 28,
    paddingVertical: 0,
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
    textAlign: "center",
  },
  inlineTimePeriodButton: {
    marginLeft: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  inlineTimePeriodText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 15,
    textTransform: "lowercase",
  },
  inputActionButton: {
    position: "absolute",
    right: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarIcon: {
    width: 18,
    height: 18,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: 4,
    overflow: "hidden",
  },
  calendarIconHeader: {
    height: 5,
    backgroundColor: colors.primary,
  },
  calendarIconGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 2,
    gap: 2,
    justifyContent: "center",
  },
  calendarIconDot: {
    width: 3,
    height: 3,
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  clockIcon: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  clockFace: {
    position: "absolute",
    width: 16,
    height: 16,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  clockHandVertical: {
    position: "absolute",
    width: 1.5,
    height: 5,
    backgroundColor: colors.primary,
    top: 4,
  },
  clockHandHorizontal: {
    position: "absolute",
    width: 4,
    height: 1.5,
    backgroundColor: colors.primary,
    left: 9,
  },
  filterInputInvalid: {
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerBackground,
  },
  timeModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(29, 27, 32, 0.32)",
    paddingHorizontal: 18,
    justifyContent: "center",
  },
  timeModalCard: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 18,
  },
  timeModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  timeModalCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.subtleBackground,
    borderWidth: 1,
    borderColor: colors.border,
  },
  timeModalCloseText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  timePickerTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  timeWheelWrap: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: TIME_WHEEL_ITEM_HEIGHT * 3,
  },
  timeWheelSelectionBand: {
    position: "absolute",
    left: 0,
    right: 0,
    top: TIME_WHEEL_ITEM_HEIGHT,
    height: TIME_WHEEL_ITEM_HEIGHT,
    borderRadius: 18,
    backgroundColor: colors.subtleBackground,
  },
  timeWheelColumn: {
    width: 88,
    maxHeight: TIME_WHEEL_ITEM_HEIGHT * 3,
  },
  timePeriodColumn: {
    width: 92,
    maxHeight: TIME_WHEEL_ITEM_HEIGHT * 3,
  },
  timeWheelContent: {
    paddingVertical: TIME_WHEEL_ITEM_HEIGHT,
  },
  timeWheelItem: {
    height: TIME_WHEEL_ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
  },
  timeWheelText: {
    color: colors.mutedText,
    fontFamily: fonts.regular,
    fontSize: 52,
    lineHeight: 56,
  },
  timeWheelTextSelected: {
    color: colors.primary,
    fontFamily: fonts.bold,
  },
  timePeriodText: {
    fontSize: 34,
    lineHeight: 46,
  },
  timeWheelDivider: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 52,
    lineHeight: 56,
    marginHorizontal: 4,
  },
  calendarCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 14,
    marginBottom: 16,
  },
  calendarHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  calendarNavButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.subtleBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarNavText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  calendarTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  calendarWeekRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  calendarWeekLabel: {
    width: "15%",
    textAlign: "center",
    color: colors.secondary,
    fontFamily: fonts.bold,
    fontSize: 12,
  },
  calendarDateButton: {
    width: "15%",
    aspectRatio: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.subtleBackground,
  },
  calendarDateButtonSelected: {
    backgroundColor: colors.primary,
  },
  calendarDateButtonDisabled: {
    opacity: 0.35,
  },
  calendarDateText: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 13,
  },
  calendarDateTextMuted: {
    color: colors.mutedText,
  },
  calendarDateTextSelected: {
    color: colors.white,
  },
  calendarDateTextDisabled: {
    color: colors.mutedText,
  },
  calendarDoneButton: {
    marginTop: 10,
    borderRadius: 12,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    alignItems: "center",
  },
  calendarDoneButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  helperText: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 6,
  },
  previewCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#efc3c3",
    backgroundColor: "#fbf2f2",
    padding: 14,
    marginBottom: 16,
  },
  previewTitle: { color: colors.primary, fontFamily: fonts.bold, fontSize: 15, marginBottom: 10 },
  previewChipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  previewChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  previewChipText: { color: colors.text, fontFamily: fonts.regular, fontSize: 12 },
  previewChipRemoveButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.subtleBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  previewChipRemoveText: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 11,
    lineHeight: 11,
  },
  previewEmptyText: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 18,
  },
  stateCard: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.subtleBackground,
    padding: 16,
    alignItems: "center",
  },
  stateText: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 13,
    marginTop: 8,
    textAlign: "center",
  },
  resultsShell: {
    marginTop: 12,
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  defaultContentShell: {
    marginTop: 12,
  },
  resultsAppName: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 20,
    textAlign: "center",
    marginBottom: 4,
  },
  resultsTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 24,
    textAlign: "center",
  },
  resultsSubtitle: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 14,
    textAlign: "center",
    marginTop: 6,
    marginBottom: 18,
  },
  resultsFooter: {
    marginTop: 12,
    alignItems: "center",
  },
  resultsBlock: {},
  roomCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 14,
    marginBottom: 12,
  },
  roomHeader: { flexDirection: "row", alignItems: "flex-start" },
  roomInfoPressable: { flex: 1, paddingRight: 12 },
  roomName: { color: colors.text, fontFamily: fonts.bold, fontSize: 18 },
  roomMeta: { color: colors.secondary, fontFamily: fonts.regular, fontSize: 13, marginTop: 4 },
  expandButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.subtleBackground,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  expandButtonText: { color: colors.primary, fontFamily: fonts.bold, fontSize: 22, lineHeight: 22 },
  roomLoader: { marginTop: 12 },
  expandedSection: { marginTop: 14 },
  detailCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.subtleBackground,
    padding: 12,
  },
  detailText: { color: colors.text, fontFamily: fonts.regular, fontSize: 13, marginBottom: 4 },
  detailLabel: { fontFamily: fonts.bold },
  schedulePreviewCard: {
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.subtleBackground,
    padding: 12,
  },
  schedulePreviewTitle: { color: colors.primary, fontFamily: fonts.bold, fontSize: 16 },
  weekNavRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 10,
  },
  weekNavButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  weekNavText: { color: colors.primary, fontFamily: fonts.bold, fontSize: 18 },
  weekNavTextDisabled: { color: colors.mutedText },
  schedulePreviewSubtitle: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 18,
  },
  schedulePreviewGreen: { color: colors.successText, fontFamily: fonts.bold },
  schedulePreviewYellow: { color: "#fdba74", fontFamily: fonts.bold },
  schedulePreviewRed: { color: colors.dangerText, fontFamily: fonts.bold },
  schedulePreviewHelperText: {
    color: colors.secondary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 12,
    marginBottom: -8,
  },
  schedulePreviewHelperTextBold: {
    fontFamily: fonts.bold,
  },
  reserveSelectedButton: {
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  reserveSelectedButtonDisabled: {
    backgroundColor: colors.border,
  },
  reserveSelectedButtonError: {
    backgroundColor: colors.dangerBackground,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
  },
  reserveSelectedButtonText: {
    color: colors.white,
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  reserveSelectedButtonTextError: {
    color: colors.mutedText,
  },
  reserveSelectedButtonTextDisabled: {
    color: colors.mutedText,
  },
  scheduleDateGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 10,
    marginBottom: 12,
  },
  scheduleDateChip: {
    width: "31%",
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  scheduleDateChipSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  scheduleDateChipDisabled: { opacity: 0.55 },
  scheduleDateDay: { color: colors.secondary, fontFamily: fonts.bold, fontSize: 12, marginBottom: 4 },
  scheduleDateValue: { color: colors.text, fontFamily: fonts.bold, fontSize: 13 },
  scheduleDateTextSelected: { color: colors.white },
  scheduleDateTextDisabled: { color: colors.mutedText },
  timeSlotSection: { marginTop: 12 },
  timeSlotSectionTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 14, marginBottom: 8 },
  timeSlotCard: { borderRadius: 12, borderWidth: 1, padding: 12, marginBottom: 8 },
  timeSlotHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  timeSlotTime: { fontFamily: fonts.bold, fontSize: 13, flex: 1, paddingRight: 8 },
  timeSlotBadge: { fontFamily: fonts.bold, fontSize: 11, textTransform: "capitalize" },
  timeSlotDescription: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 18 },
});

export default styles;
